### ISSUE TITLE
Error when calling :MerginalToggle inside Merginal buffer 

### ISSUE THREAD

**Issue by nsue** [idanarye/vim-merginal#11]
I get the following error when I call `:MerginalToggle` inside the Merginal buffer (although the buffer does successfully close):

```
Error detected while processing function <SNR>108_toggleBasedOnMergeMode..merginal#closeMerginalBuffer:
line   14:
E16: Invalid range: 2wincmd w
Error detected while processing function <SNR>108_toggleBasedOnMergeMode:
line   27:
E171: Missing :endif
```

**Comment by idanarye** [comment]
The erroneous line is:
```vim
            execute l:currentWindow.'wincmd w'
```
(I really wish Vim error messages will give line number from the beginning of the file, not the function. VimScript is not SmallTalk...)

If the Merginal buffer resides in the last(lower/rightmost) window, and you close it, there is no longer a window with that number.

Should be easy enough to fix
