### ISSUE TITLE
Rebase error on newer git versions

### ISSUE THREAD

**Issue by ajgon** [idanarye/vim-merginal#16]
I'm currently using `git version 2.7.3` and it appears, that `.git/rebase-apply/msg-clean` file is no longer present while doing rebase. (Worked fine in `2.5.4`). Invoking `rb` shortcut, produces following error:

```
Error detected while processing function merginal#invokeKeyMap[1]..379[16]..378[5]..<SNR>71_rebaseBranchUnderCursor[7]..merginal#openRebaseConflictsBuffer[10]..merginal#tryRefreshRebaseConflictsBuffer:
line    2:
E484: Can't open file /Users/ajgon/Projects/dummy/.git/rebase-apply/msg-clean
```

**Comment by idanarye** [comment]
Fix is in develop(as part of a huge refactor)
