### ISSUE TITLE
Creating new branch replaces existing buffer

### ISSUE THREAD

**Issue by invsblduck** [idanarye/vim-merginal#18]
Hi there, thanks for creating this plugin.  Seems like something I'm definitely interested in.

I hit such a nasty bug in my first operation with it, that I feel like I should report it in as much detail as possible for you....seems like you've put a lot of effort into this.

Here goes:
With only one buffer open for a file named `myfile.py` (no other buffers, tabs, etc), I wrote changes to disk with `:w`.  So I had a modified file in my working tree that wasn't staged to the index.  I then used `:MerginalToggle` to open the Merginal buffer.  I pressed `A` to create a new branch and typed `newbranch` as the name.  The output was:  
```
Branch `devel` to: newbranch[output] Switched to a new branch 'newbranch'
[output] M        myfile.py
Press ENTER or type command to continue
```
However, after I pressed Return to dismiss the output, the contents of the buffer that was `myfile.py` had been replaced with Merginal contents!!  This data appeared as new, unsaved data&#8212;but to my surprise, the buffer number and current filename had NOT changed!  The current file being edited was still `myfile.py` and was now marked as `[Modified]`... I was confused and in shock to say the least!  The original Merginal split was still open to the left.  The `modifiable` flag was off in my file buffer, so I couldn't make any edits to the contents, but I actually went so far as to *save* the buffer because I was in such disbelief that it clobbered my file, and in fact, yes, here was the result:
```bash
workstation [~/dev/project]$ cat myfile.py
Press ? for help

  devel
  foo
  master
* newbranch
  remotes/origin/HEAD -> origin/master
  remotes/origin/master
workstation [~/dev/project]$
```

Sorry I don't have cycles to debug it or read the vimscript, but it scared the pants off me so bad that I'm probably going to start reading more plugin code before I ever use a new one for the first time.  :-)

Thanks

**Comment by idanarye** [comment]
I couldn't reproduce this, but I think I know what happens. I was working under the assumption that a refresh can only be triggered from the Merginal buffer, so I just made it update the current buffer. For some odd reason a refresh was triggered from the buffer of your file, causing Merginal to write to it instead of to it's own buffer.

I'm terribly sorry for the loss of your code. I've pushed and uploaded a bugfix that makes sure Merginal only updates it's own buffer.
