### ISSUE TITLE
numbers on the merginal buffers

### ISSUE THREAD

**Issue by sfahlberg** [idanarye/vim-merginal#19]
Hi there, I love merginal! Just curious whether there's any way to get numbers so I can more quickly navigate around. thanks!

**Comment by idanarye** [comment]
:laughing: disabling numbering in the Merginal buffers was requested in ticket #1. I guess everyone have their own tastes...

Anyways, Merginal buffers are always renamed to `Merginal:<something>` using the `:file` command, which triggers the `BufFilePost` event. This happens after I `:setlocal nonumber` and `:setlocal norelativenumber`, so you can hook to this event and set them yourself:

```vim
autocmd BufFilePost Merginal:* setlocal number

" And if you want relative numbers:
autocmd BufFilePost Merginal:* setlocal relativenumber
```

**Comment by sfahlberg** [comment]
this is awesome! thanks! would be great to add this to the docs for other folks
