### ISSUE TITLE
Does this work with VIM8 and git2?

### ISSUE THREAD

**Issue by alex-shamshurin** [idanarye/vim-merginal#22]
`:Merginal` shows error `Error during processing function merginal#openMerginalBuffer[5]..merginal#modulelib#createObject[4]..<SNR>265_populate:`

`no key in dictionary: branchList`

Line 2 and Line 5.

(it's a translate, my vim shows errors in russian)

**Comment by alex-shamshurin** [comment]
In this line `let l:module = s:modules[a:moduleName]`

**Comment by idanarye** [comment]
It should work with VIM8 - it's probably a bug.

Was your repository in merge/rebase/cherry-pick mode when you tried it?

**Comment by alex-shamshurin** [comment]
No, clean state

**Comment by alex-shamshurin** [comment]
I would make a PR if I knew VIMLang, so I can't fix it

**Comment by idanarye** [comment]
What happens when you run this:
```vim
echo globpath(&runtimepath, 'autoload/merginal/buffers/branchList.vim')
```

**Comment by alex-shamshurin** [comment]
Looks like a correct path (I do not know how to copy out the command output)

**Comment by idanarye** [comment]
OK, I just noticed something - the exception message is wrong. At least, it's different from what I get.

I've pushed a fix to `develop`. Please check that it works for you.

**Comment by alex-shamshurin** [comment]
Yes, I wrote - it's my translation. Because my vim is in russian (windows 10 bash)

**Comment by alex-shamshurin** [comment]
Now it works, thanks
