### ISSUE TITLE
Git pull and push does not work if there are two remotes

### ISSUE THREAD

**Issue by alex-shamshurin** [idanarye/vim-merginal#26]
When I had only one git remote repo it worked as expected - `ps` and `pl` on the branch did git pull. Now it opens a prompt when I have to choose which remote to pull from or push to, but when remote is chosen nothing happens.

**Comment by idanarye** [comment]
So, as it turns out, I am an idiot. My custom `merginal#util#inputList` returns -1 instead of 0 when nothing is chosen, but I was checking if the result is `<= 0` to see if the user canceled the choice...

**Comment by alex-shamshurin** [comment]
Thanks

**Comment by alex-shamshurin** [comment]
It still does not work! It just ask from which remote to pull, but after the answer nothing happens

**Comment by idanarye** [comment]
Do you happen to be getting an `E117: Unknown function: termopen` error?

If that's not it - are on on `develop` or `master`? Because apparently I haven't made a release since fixing this...

**Comment by idanarye** [comment]
Just made a new releade(v2.1.0) that should fix both problems.

**Comment by alex-shamshurin** [comment]
I got no errors, nothing happens (I have not installed the update yet)

**Comment by alex-shamshurin** [comment]
It still doesn't work. When I select a remote by entering its number - still nothing happens
