### ISSUE TITLE
disable remote branches in branchList

### ISSUE THREAD

**Issue by cIvanrc** [idanarye/vim-merginal#43]
first of all, thanks for this plugin is very helpful

i'm asking if there is a way to disable the remote branches in the branch list

because if the developer is changing only/most frequently in local branches, a big list of remote branches isn't great, there is an option to filter/search but it could be better if it only displays local branches

**Comment by chris542** [comment]
I second this. I actually came back here to ask the same thing

**Comment by cIvanrc** [comment]
@chris542 you can edit your local plugin, that was my solution 

https://github.com/idanarye/vim-merginal/blob/62755dd4e9efb377f72d82b052a9810685c77e91/autoload/merginal/buffers/immutableBranchList.vim#L4

![image](https://user-images.githubusercontent.com/29314633/99350469-15a66880-2864-11eb-97cf-5bbdaef29c5c.png)

**Comment by chris542** [comment]
@cIvanrc Thank you!! If this repo is no longer maintained, i might as well fork it

**Comment by chris542** [comment]
@cIvanrc  I've made a PR and it has been merged. You should be able to close this issue 👍
