### ISSUE TITLE
Merginal Toggle seems to fail after updating version

### ISSUE THREAD

**Issue by opensourcegeek** [idanarye/vim-merginal#49]
I've just updated to latest version of the plugin and it started failing for me with the following message. I'm on neovim, but this plugin was working till I updated it though. Any ideas on what could be causing please?

```
Error detected while processing function <SNR>143_toggleBasedOnMergeMode[18]..merginal#openMerginalBuffer[10]..399[39]..408[9]..383[2]..396[1]..395[4]..<SNR>230_repo_git_command:
line    1:
E605: Exception not caught: fugitive: fugitive#repo().git_command(...) has been replaced by FugitiveShellCommand(...)
Error detected while processing function <SNR>143_toggleBasedOnMergeMode[18]..merginal#openMerginalBuffer[10]..399[39]..408[9]..383:
line    2:
E171: Missing :endif
Error detected while processing function <SNR>143_toggleBasedOnMergeMode[18]..merginal#openMerginalBuffer[10]..399:
line   39:
E171: Missing :endif
Error detected while processing function <SNR>143_toggleBasedOnMergeMode:
line   18:
E171: Missing :endif

```

**Comment by opensourcegeek** [comment]
Had a quick look into the issue, it seems to be because you've fixed the issue on the develop branch but the plugin has not been released yet since then. If so could I use the develop branch for now? Are there any other fundamental issues blocking from releasing  please?

**Comment by idanarye** [comment]
No reason really. Making a release now.

**Comment by idanarye** [comment]
Done
