### ISSUE TITLE
Commit 8378b329b8ffd7cc1991cabcbe97a203968ae4be of Fugitive breaks merginal

### ISSUE THREAD

**Issue by idanarye** [idanarye/vim-merginal#52]
https://github.com/tpope/vim-fugitive/commit/8378b329b8ffd7cc1991cabcbe97a203968ae4be drops many public functions from Fugitive's API - including `fugitive#repo()`, which Merginal heavily relies on.

Until I can fix this, commit 92c73bb0507338441733198d630a1fe5e7fdac3a of Fugitive should be used.

**Comment by fjfnaranjo** [comment]
@idanarye Do you need any help with this? I'm not very well versed in vim-script but if you point to the potential api broken in vim-merginal source I can take a look and hack something quick.

**Comment by idanarye** [comment]
It's not exactly "quick". `fugitive#repo()` was returning an object which I used for doing Git stuff on the "correct" (as decided by Fugitive) repository, but now I need to replace it with standalone functions - which means I need to figure out what's Fugitive's new way to get the current repository and how to pass it to these standalone functions.

I'm hoping to get to it today, but I was hoping to get to it yesterday and gave it up because my cat was sleeping on my computer chair and I did not want to disturb him - which shows a lot about my work ethics...

**Comment by fjfnaranjo** [comment]
As another cat lover, I completely understand and approve your decision. I would totally hire you, if you promised to bring your cat to the office sometimes.

**Comment by idanarye** [comment]
I think `fugitive#PrepareDirEnvGitFlagsArgs` is the key. Just need to figure out how to use it...

**Comment by fjfnaranjo** [comment]
Thanks! :heart:
