### ISSUE TITLE
Error detected while processing function merginal#openMerginalBuffer

### ISSUE THREAD

**Issue by asnever** [idanarye/vim-merginal#53]
It seems like in updated Fugitive, fugitive#repo has been replaced with by FugitiveFind, so now my Merginal don't work (it throws uncaught exception)

Merginal: version 2.2.1
Fugitive: version 3.7

**Comment by idanarye** [comment]
Right... already fixed that, but did not make a release. Will do now.

**Comment by asnever** [comment]
Thanks!
