### ISSUE TITLE
new mf command produces error

### ISSUE THREAD

**Issue by wikimatze** [idanarye/vim-merginal#9]
The `mn` command is working perfect, but when I created a branch, then went back to master, fire up `:Merginal`, go with the cursor over the new branch and press `mf` I get the following error:

```vim
Error detected while processing function <SNR>168_mergeBranchUnderCursorUsingFugitive:                                                                                                        
line    3:                                                                                                                                                                                    
E121: Undefined variable: l:branchName                                                                                                                                                        
E15: Invalid expression: ':Gmerge '.l:branchName.handle
```

Can you reproduce this?

**Comment by idanarye** [comment]
`mf` is not new - as I've commented on #8, `mf` was already occupied for merging using Fugitive's `:Gmerge` command. It has nothing to do with fast-forward.

Still, it's a bug, so thanks for noticing it. It seems to be broken from July 2014 though - I guess nobody uses that feature...

**Comment by wikimatze** [comment]
Thanks for fixing.

**Comment by idanarye** [comment]
Sorry for taking so long...

**Comment by wikimatze** [comment]
No problem, I have so many unfixed things and sometimes in just takes some time.
